# WARNING: This file will be overwritten if CS50 vagrant is reprovisioned.
# If you prefer something else, create ~/.bashrc_logout.custom

# This file is sourced by bash at the close of every login shell.  For
# more info type `man bash'.

if [ -r ~/.bashrc_logout.custom ]; then
    source ~/.bashrc_logout.custom
else 
    echo logging out...
fi

# --------------------------------------------------------------------
