# WARNING: This file will be overwritten if CS50 vagrant is reprovisioned.
# If you prefer something else, create ~/.bashrc.custom

if [ -r ~/.bashrc.custom ]; then
    source ~/.bashrc.custom
elif [ -r ~/.bashrc.default ]; then
    source ~/.bashrc.default
fi

